### ISSUE TITLE
Chi**0.5 factor missing in the denominator of mass loss term

### ISSUE THREAD

**Issue by dutta-alankar** [dfielding14/MultiphaseGalacticWind#1]
Line 185 in `MultiphaseGalacticWind.py`
`Mdot_loss    = Mdot_coefficient * 3.0 * M_cloud * v_turb_cold / r_cloud`
needs to be changed to 
`Mdot_loss    = Mdot_coefficient * 3.0 * M_cloud * v_turb_cold / (r_cloud*AreaBoost)`

**Comment by dfielding14** [comment]
The way the code is written is correct. 

The chi**-0.5 scaling comes from the definition of `v_turb_cold  = v_turb * chi**ColdTurbulenceChiPower` where `ColdTurbulenceChiPower=-0.5`. 

As you can see in section 3.3 of the paper we do not include the `AreaBoost` in the mass loss term. 

It has been a while since I looked into this but it may be that you get identical behavior if you define `ColdTurbulenceChiPower=0.0` and include the `AreaBoost` in the way you suggested, so it is really just a matter of the physical interpretation as opposed to changing the outcome.
